#pragma config(Motor,  port1,           RightDrive,    tmotorVex393_HBridge, openLoop, driveRight)
#pragma config(Motor,  port6,           ClawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           ArmMotor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          LeftMotor,     tmotorVex393_HBridge, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
	VEXRT[Ch2] = motor[RightDrive];
	VexRT[Ch3] = motor[LeftDrive];
	if(vexRT[Btn6UXmtr2] == 1)
		motor[ArmMotor] = 127;
	else if(VexRT[Btn6DXmtr2] == 1)
		motor[ArmMotor] = -127;
	else
		motor[ArmMotor] = 0;

	if(vexRT[Btn5UXmtr2] == 1)
		motor[ClawMotor] = 127;
	else if(vexRT[Btn5DXmtr2] == 1)
		motor[ClawMotor] = -127;
	else
		motor[ClawMotor] = 0;
	}
}
